Repository java-heroes/ParkingControlSystem, pull requests merged in 2021-07, with the labels that each got.

#2 Feature/layered architecture
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/ExampleController.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/ExampleService.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/ExampleManager.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/core/ExampleCoreClass.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/abstracts/ExampleDao.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/concretes/ExampleDao.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/abstracts/Example.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/Example.java
Labels: good first issue

#3 Develop
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/ExampleController.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/ExampleService.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/ExampleManager.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/core/ExampleCoreClass.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/abstracts/ExampleDao.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/concretes/ExampleDao.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/abstracts/Example.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/Example.java
Labels: good first issue

#15 🔨Add database configuration to Application properties
  ParkingControlSystem/src/main/resources/application.properties
Labels: enhancement

#16 Develop
  ParkingControlSystem/src/main/resources/application.properties
Labels: enhancement

#17 🔨Create user table
  ParkingControlSystem/pom.xml
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/ParkingControlSystemApplication.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/Example.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/User.java
  ParkingControlSystem/src/main/resources/application.properties
Labels: enhancement

#19 Develop-Update Readme file
  ParkingControlSystem/pom.xml
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/ParkingControlSystemApplication.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/Example.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/User.java
  ParkingControlSystem/src/main/resources/application.properties
  README.md
Labels: documentation

#20 🔨Create core operations
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/core/ExampleCoreClass.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/core/utilities/results/DataResult.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/core/utilities/results/ErrorDataResult.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/core/utilities/results/ErrorResult.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/core/utilities/results/Result.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/core/utilities/results/SuccessDataResult.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/core/utilities/results/SuccessResult.java
Labels: enhancement

#21 Added core operations to develop
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/core/ExampleCoreClass.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/core/utilities/results/DataResult.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/core/utilities/results/ErrorDataResult.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/core/utilities/results/ErrorResult.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/core/utilities/results/Result.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/core/utilities/results/SuccessDataResult.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/core/utilities/results/SuccessResult.java
Labels: enhancement

#22 Feature/owner table crud
  ParkingControlSystem/bin/.mvn/wrapper/MavenWrapperDownloader.class
  ParkingControlSystem/bin/pom.xml
  ParkingControlSystem/bin/src/main/java/kodluyoruz/ParkingControlSystem/ParkingControlSystemApplication.class
  ParkingControlSystem/bin/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/ExampleController.class
  ParkingControlSystem/bin/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/ExampleService.class
  ParkingControlSystem/bin/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/ExampleManager.class
  ParkingControlSystem/bin/src/main/java/kodluyoruz/ParkingControlSystem/core/ExampleCoreClass.class
  ParkingControlSystem/bin/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/abstracts/ExampleDao.class
  ParkingControlSystem/bin/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/concretes/ExampleDao.class
  ParkingControlSystem/bin/src/main/java/kodluyoruz/ParkingControlSystem/entities/abstracts/Example.class
  ParkingControlSystem/bin/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/User.class
  ParkingControlSystem/bin/src/main/resources/application.properties
  ParkingControlSystem/bin/src/test/java/kodluyoruz/ParkingControlSystem/ParkingControlSystemApplicationTests.class
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/ExampleController.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/OwnerController.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/ExampleService.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/OwnerService.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/ExampleManager.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/OwnerManager.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/abstracts/ExampleDao.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/abstracts/OwnerDao.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/Owner.java
Labels: enhancement

#23 Develop
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/OwnerController.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/OwnerService.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/OwnerManager.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/abstracts/OwnerDao.java
Labels: enhancement

#24 Feature/create carpark
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/CarPark.java
Labels: enhancement

#25 Develop
  ParkingControlSystem/bin/.mvn/wrapper/MavenWrapperDownloader.class
  ParkingControlSystem/bin/pom.xml
  ParkingControlSystem/bin/src/main/java/kodluyoruz/ParkingControlSystem/ParkingControlSystemApplication.class
  ParkingControlSystem/bin/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/ExampleController.class
  ParkingControlSystem/bin/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/ExampleService.class
  ParkingControlSystem/bin/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/ExampleManager.class
  ParkingControlSystem/bin/src/main/java/kodluyoruz/ParkingControlSystem/core/ExampleCoreClass.class
  ParkingControlSystem/bin/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/abstracts/ExampleDao.class
  ParkingControlSystem/bin/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/concretes/ExampleDao.class
  ParkingControlSystem/bin/src/main/java/kodluyoruz/ParkingControlSystem/entities/abstracts/Example.class
  ParkingControlSystem/bin/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/User.class
  ParkingControlSystem/bin/src/main/resources/application.properties
  ParkingControlSystem/bin/src/test/java/kodluyoruz/ParkingControlSystem/ParkingControlSystemApplicationTests.class
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/ExampleController.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/OwnerController.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/ExampleService.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/OwnerService.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/ExampleManager.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/OwnerManager.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/core/ExampleCoreClass.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/core/utilities/results/DataResult.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/core/utilities/results/ErrorDataResult.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/core/utilities/results/ErrorResult.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/core/utilities/results/Result.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/core/utilities/results/SuccessDataResult.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/core/utilities/results/SuccessResult.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/abstracts/ExampleDao.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/abstracts/OwnerDao.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/CarPark.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/Owner.java
Labels: enhancement

#26 Feature/user crud
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/UsersController.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/UserService.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/UserManager.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/abstracts/UserDao.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/User.java
Labels: enhancement

#27 Develop
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/OwnersController.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/UsersController.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/UserService.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/UserManager.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/abstracts/UserDao.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/CarPark.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/Owner.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/User.java
Labels: enhancement

#28 Feature/create park rental user relation
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/ParkRental.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/User.java
Labels: enhancement

#29 Develop
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/ParkRental.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/User.java
Labels: enhancement

#30 Feature/rental detail table and park rental relation
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/ParkRental.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/RentalDetail.java
Labels: enhancement

#31 Develop
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/ParkRental.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/RentalDetail.java
Labels: enhancement

#32 🔀 Feature/car park park layout crud relation business rules
  ParkingControlSystem/.gitignore
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/CarParksController.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/ParkLayoutsController.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/CarParkService.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/ParkLayoutService.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/CarParkManager.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/ParkLayoutManager.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/abstracts/CarParkDao.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/abstracts/ParkLayoutDao.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/CarPark.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/Owner.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/ParkLayout.java
Labels: enhancement

#33 🔀Develop
  ParkingControlSystem/.gitignore
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/CarParksController.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/ParkLayoutsController.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/CarParkService.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/ParkLayoutService.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/CarParkManager.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/ParkLayoutManager.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/abstracts/CarParkDao.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/abstracts/ParkLayoutDao.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/CarPark.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/Owner.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/ParkLayout.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/ParkRental.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/RentalDetail.java
Labels: enhancement

#34 Feature/relation with park rental and park layout
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/ParkLayout.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/ParkRental.java
Labels: enhancement

#35 Develop
  ParkingControlSystem/.gitignore
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/CarParksController.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/ParkLayoutsController.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/CarParkService.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/ParkLayoutService.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/CarParkManager.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/ParkLayoutManager.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/abstracts/CarParkDao.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/abstracts/ParkLayoutDao.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/CarPark.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/Owner.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/ParkLayout.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/ParkRental.java
Labels: enhancement

#36 Feature/crud operations of parkrental table
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/ParkRentalsController.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/ParkRentalService.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/ParkRentalManager.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/abstracts/ParkRentalDao.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/ParkLayout.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/ParkRental.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/RentalDetail.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/User.java
Labels: enhancement

#37 Develop
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/ParkRentalsController.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/ParkRentalService.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/ParkRentalManager.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/abstracts/ParkRentalDao.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/ParkLayout.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/ParkRental.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/RentalDetail.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/User.java
Labels: enhancement

#38 Develop
  ParkingControlSystem/.gitignore
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/CarParksController.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/ParkLayoutsController.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/ParkRentalsController.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/CarParkService.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/ParkLayoutService.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/ParkRentalService.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/CarParkManager.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/ParkLayoutManager.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/ParkRentalManager.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/abstracts/CarParkDao.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/abstracts/ParkLayoutDao.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/abstracts/ParkRentalDao.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/CarPark.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/Owner.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/ParkLayout.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/ParkRental.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/RentalDetail.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/User.java
Labels: enhancement

#39 Feature/rental detail crud operations
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/api/controllers/RentalDetailsController.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/ParkRentalService.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/abstracts/RentalDetailService.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/ParkRentalManager.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/business/concretes/RentalDetailManager.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/dataAccess/abstracts/RentalDetailDao.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/ParkRental.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/RentalDetail.java
  ParkingControlSystem/src/main/java/kodluyoruz/ParkingControlSystem/entities/concretes/User.java
Labels: enhancement
